version: "3.8"
services:
  postgres:
    restart: always
    container_name: todo_postgres
    image: 'postgres:13.8-alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    volumes:
      - postgres:/var/lib/postgresql/data/
    networks:
      - default

volumes:
  postgres:

networks:
  default: