service: todo-service
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.9
  httpApi:
    cors: true

functions:
  create-task:
    handler: src/infra/functions/create-task.handle
    events:
      - httpApi:
          path: /task
          method: post