service: todo-service
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.9
  httpApi:
    cors: true

functions:
  create-task:
    handler: src/infra/functions/create-task.handle
    events:
      - httpApi:
          path: /task
          method: post

  list-task:
    handler: src/infra/functions/list-tasks.handle
    events:
      - httpApi:
          path: /task
          method: get

  delete-task:
    handler: src/infra/functions/delete-task.handle
    events:
      - httpApi:
          path: /task
          method: delete

  do-task:
    handler: src/infra/functions/do-task.handle
    events:
      - httpApi:
          path: /task/do
          method: put